### ISSUE TITLE
Why using Gaussian Filter in MDA ?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [bcmi/DIRL#1]
Very interesting work, some doubts as shown in the title.
----------------------------------------------------------------
It also makes me wonder that you said "the ground-truth mask M is resized to match the resolution of each A_{k}" in your paper,  but I found that the [code](https://github.com/bcmi/DIRL-Inharmonious-Region-Localization/blob/2c1722b240246d5cb318314254b2e3d98bc09b37/model/DIRL.py#L373) seemed to do the opposite. 

Looking forward to your reply!

**Comment by jimleungjing** [comment]
Thanks for your attention!
1) Gaussian Filter is expected to enlarge the attention region to make final mask prediction more robust.(In some extreme cases, one can observe that attention region might cover few part of ground truth, yielding a poor quality mask). However, due to limited time, we conduct very few experiments, and found that the improvement is imperceptible when the model is equipped with Gaussian Filter. We will clean the Gaussian Filter code in future.
2) I forgot to revise the sentence.  Resizing ground-truth(GT) mask M to A_{k} will loss clear boundary when the target resolution is too small(e.g., 256x256->16x16), and the resized GT mask will be empty in some extreme cases. These resized GTs will lead to wrong guidance and hurt performance. Resizing A_{k} to match the GT resolution is much better, since interpolation operation in mask prediction is differentiable.

**Comment by CSer-Tang-hao** [comment]
Thanks for your feedback!
I also found in your code that using [iou_loss](https://github.com/bcmi/DIRL-Inharmonious-Region-Localization/blob/2c1722b240246d5cb318314254b2e3d98bc09b37/dirl_train.py#L45) in [bce_ssim_loss](https://github.com/bcmi/DIRL-Inharmonious-Region-Localization/blob/2c1722b240246d5cb318314254b2e3d98bc09b37/dirl_train.py#L37), which is not mentioned in your paper. 
I wonder whether **iou_loss** can greatly improve the final result.

**Comment by jimleungjing** [comment]
> Thanks for your feedback!
> I also found in your code that using [iou_loss](https://github.com/bcmi/DIRL-Inharmonious-Region-Localization/blob/2c1722b240246d5cb318314254b2e3d98bc09b37/dirl_train.py#L45) in [bce_ssim_loss](https://github.com/bcmi/DIRL-Inharmonious-Region-Localization/blob/2c1722b240246d5cb318314254b2e3d98bc09b37/dirl_train.py#L37), which is not mentioned in your paper.
> I wonder whether **iou_loss** can greatly improve the final result.

**iou_loss** is aim to improve the IoU of the final inharmonious region prediction, and it indeed improves IoU score and slightly improves other two metrics.
